<div class="home-line">
  <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_line_text')->toHtml(); ?>
</div>

<script>
  require([
    'jquery',
    'slick'
  ], function($) {
    $(document).ready(function() {
      $('.home-line').slick({
        //autoplay: true,
        arrows: false,
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow: 3,
        slidesToScroll: 3,
        responsive: [{
            breakpoint: 1024,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1,
              infinite: true,
              dots: false
            }
          },
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          }
        ]
      });
    });
  });
</script>