<div class="outdoor-inspiration">
  <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_inspiration')->toHtml(); ?>
</div>

<script>
  require([
    'jquery',
    'slick'
  ], function($) {
    $(document).ready(function() {
      $('.inspiration-images').slick({
        autoplay: true,
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow: 5,
        slidesToScroll: 1,
        nextArrow: '<button class="slick-next" aria-label="Next" type="button" style="display: block;"><i class="fa fa-angle-right" aria-hidden="true"></i></button>',
        prevArrow: '<button class="slick-prev" aria-label="Previous" type="button" style="display: block;"><class="fa fa-angle-right" aria-hidden="true"></i></button>',
        responsive: [{
            breakpoint: 1024,
            settings: {
                rows: 2,
                slidesToShow: 3,
                slidesToScroll: 1,
            }
          },
          {
            breakpoint: 600,
            settings: {
                rows: 2,
                slidesToShow: 2,
                slidesToScroll: 1
            }
          },
          {
            breakpoint: 480,
            settings: {
                rows: 2,
                slidesToShow: 2,
                slidesToScroll: 1
            }
          }
        ]
      });
    });
  });
</script>