<div class="outdoor-inspiration">
  <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_inspiration')->toHtml(); ?>
</div>
<div class="outdoor-inspiration-mobile">
  <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('home_inspiration_mobile')->toHtml(); ?>
</div>

<script>
  require([
    'jquery',
    'slick'
  ], function($) {
    $(document).ready(function() {
      $('.inspiration-images').slick({
        //autoplay: true,
        dots: false,
        infinite: true,
        speed: 300,
        slidesToShow: 5,
        slidesToScroll: 1,
        responsive: [{
            breakpoint: 1024,
            settings: {
                rows: 2,
                slidesToShow: 3,
                slidesToScroll: 1,
            }
          },
          {
            breakpoint: 600,
            settings: {
                rows: 2,
                slidesToShow: 2,
                slidesToScroll: 1,
                arrows: false,
                dots: true,
            }
          },
          {
            breakpoint: 480,
            settings: {
                rows: 2,
                slidesToShow: 2,
                slidesToScroll: 1,
                arrows: false,
                dots: true,
            }
          }
        ]
      });
    });
  });
</script>