<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Newsletter\Block\Subscribe $block */
?>
<div class="footer-mail">
<div class="block newsletter">
    <div class="title-big"><?= $block->escapeHtml(__('Newsletter')) ?></div>
    <div class="description">
    <?= $block->escapeHtml(__('Subscribe to our newsletter for the latest news and updates')) ?>
    </div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                        <i class="las la-angle-right"></i>
                </button>
            </div>
        </form>
    </div>
    <div class="social">
        <?php
            echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_social')->toHtml();
        ?>
    </div>
</div>
</div>
